const API="https://mystroparyaj-api.castormystro.workers.dev";
const $=id=>document.getElementById(id);
const state={user:null,me:null,events:[],wallet:{HTG:0,USD:0,EUR:0,CAD:0,DOP:0},language:localStorage.getItem("mp_language")||"ht",currency:localStorage.getItem("mp_currency")||"HTG",selectedSport:"Football",paymentMode:"deposit",paymentMethod:"moncash",adminSession:sessionStorage.getItem("mp_admin_session")||""};

const T={
ht:{home:"Akèy",sports:"Espò",tickets:"Tikè",wallet:"Bous",exchange:"Echanj",history:"Istwa",profile:"Profil mwen",agentSpace:"Espas Ajan",admin:"Administrasyon",logout:"Dekonekte",realEvents:"Evènman reyèl",heroTitle:"Parye sou match reyèl.",heroText:"Evènman foutbòl yo soti dirèkteman nan Sportmonks.",seeBets:"Gade paryaj",manageWallet:"Jere bous la",balance:"Balans",openEvents:"Evènman ouvè",account:"Kont",realMatches:"Match reyèl",liveSource:"Sportmonks • san match demo",footballFirst:"Foutbòl reyèl konekte kounye a; lòt espò yo ap bezwen sous done pa yo.",poolRule:"Peman gagnan yo soti nan pool 60% evènman an.",event:"Evènman",selection:"Seleksyon",stake:"Montan miz",currency:"Deviz",placeBet:"Achte tikè",walletText:"Depo, retrè ak balans.",mainBalance:"Balans prensipal",deposit:"Depoze",withdraw:"Retire",amount:"Montan",phone:"Nimewo telefòn",continue:"Kontinye",exchangeText:"Konvèti balans ou ak to aktyèl.",from:"Soti",to:"Pou",accountType:"Kalite kont",agentStatus:"Estati Ajan",agentCode:"Kòd Ajan",linkedAgent:"Ajan ki lye",becomeAgent:"Vin yon Ajan",agentApproval:"Admin dwe apwouve demann lan.",fullName:"Non konplè",city:"Vil / komin",address:"Adrès",sendRequest:"Voye demann Ajan",agentOnly:"Se ajan apwouve sèlman ki gen aksè.",players:"Jwè",commission:"Komisyon",linkedPlayers:"Jwè ki lye avèk ou",createPlayerTicket:"Fè fich pou yon jwè",createTicket:"Kreye tikè",cinProtected:"Zòn sa a pwoteje ak CIN.",users:"Itilizatè",openBets:"Pari ouvè",platformBalance:"Balans platfòm",agentRequests:"Demann Ajan",settleEvent:"Regle evènman",result:"Rezilta",settle:"Regle",adminVerification:"Verifikasyon Administratè",cinRequired:"Antre CIN ou pou verifye idantite w.",verify:"Verifye",loginText:"Konekte ak kont ou",login:"Konekte",register:"Enskri",forgot:"Modpas bliye",noEvents:"Pa gen evènman reyèl disponib kounye a.",oddsUnavailable:"Odds pa disponib nan plan Sportmonks ou a.",playerAccount:"Kont Jwè",agentAccount:"Kont Ajan",adminAccount:"Administratè",pending:"An atant",approved:"Apwouve",rejected:"Rejte",none:"Pa ajan"},
fr:{home:"Accueil",sports:"Sports",tickets:"Tickets",wallet:"Portefeuille",exchange:"Échange",history:"Historique",profile:"Mon profil",agentSpace:"Espace Agent",admin:"Administration",logout:"Déconnexion",realEvents:"Événements réels",heroTitle:"Pariez sur des matchs réels.",heroText:"Les événements de football viennent directement de Sportmonks.",seeBets:"Voir les paris",manageWallet:"Gérer le portefeuille",balance:"Solde",openEvents:"Événements ouverts",account:"Compte",realMatches:"Matchs réels",liveSource:"Sportmonks • aucun match démo",footballFirst:"Le football réel est connecté; les autres sports nécessitent leurs propres sources de données.",poolRule:"Les paiements des gagnants proviennent du pool de 60% de l'événement.",event:"Événement",selection:"Sélection",stake:"Mise",currency:"Devise",placeBet:"Acheter le ticket",walletText:"Dépôts, retraits et soldes.",mainBalance:"Solde principal",deposit:"Déposer",withdraw:"Retirer",amount:"Montant",phone:"Téléphone",continue:"Continuer",exchangeText:"Convertissez votre solde aux taux actuels.",from:"De",to:"Vers",accountType:"Type de compte",agentStatus:"Statut agent",agentCode:"Code agent",linkedAgent:"Agent lié",becomeAgent:"Devenir Agent",agentApproval:"L'admin doit approuver la demande.",fullName:"Nom complet",city:"Ville / commune",address:"Adresse",sendRequest:"Envoyer la demande",agentOnly:"Réservé aux agents approuvés.",players:"Joueurs",commission:"Commission",linkedPlayers:"Joueurs liés",createPlayerTicket:"Créer un ticket pour un joueur",createTicket:"Créer le ticket",cinProtected:"Cette zone est protégée par CIN.",users:"Utilisateurs",openBets:"Paris ouverts",platformBalance:"Solde plateforme",agentRequests:"Demandes agents",settleEvent:"Régler un événement",result:"Résultat",settle:"Régler",adminVerification:"Vérification Administrateur",cinRequired:"Entrez votre CIN pour vérifier votre identité.",verify:"Vérifier",loginText:"Connectez-vous à votre compte",login:"Connexion",register:"Inscription",forgot:"Mot de passe oublié",noEvents:"Aucun événement réel disponible actuellement.",oddsUnavailable:"Les cotes ne sont pas disponibles avec votre plan Sportmonks.",playerAccount:"Compte Joueur",agentAccount:"Compte Agent",adminAccount:"Administrateur",pending:"En attente",approved:"Approuvé",rejected:"Rejeté",none:"Pas agent"},
en:{home:"Home",sports:"Sports",tickets:"Tickets",wallet:"Wallet",exchange:"Exchange",history:"History",profile:"My profile",agentSpace:"Agent Space",admin:"Administration",logout:"Logout",realEvents:"Real events",heroTitle:"Bet on real matches.",heroText:"Football events come directly from Sportmonks.",seeBets:"See bets",manageWallet:"Manage wallet",balance:"Balance",openEvents:"Open events",account:"Account",realMatches:"Real matches",liveSource:"Sportmonks • no demo matches",footballFirst:"Real football is connected; other sports need their own data sources.",poolRule:"Winner payments come from the event's 60% pool.",event:"Event",selection:"Selection",stake:"Stake",currency:"Currency",placeBet:"Place bet",walletText:"Deposits, withdrawals and balances.",mainBalance:"Main balance",deposit:"Deposit",withdraw:"Withdraw",amount:"Amount",phone:"Phone",continue:"Continue",exchangeText:"Convert your wallet using current rates.",from:"From",to:"To",accountType:"Account type",agentStatus:"Agent status",agentCode:"Agent code",linkedAgent:"Linked agent",becomeAgent:"Become an Agent",agentApproval:"Admin must approve the request.",fullName:"Full name",city:"City",address:"Address",sendRequest:"Send request",agentOnly:"Approved agents only.",players:"Players",commission:"Commission",linkedPlayers:"Linked players",createPlayerTicket:"Create a ticket for a player",createTicket:"Create ticket",cinProtected:"This area is protected by CIN.",users:"Users",openBets:"Open bets",platformBalance:"Platform balance",agentRequests:"Agent requests",settleEvent:"Settle event",result:"Result",settle:"Settle",adminVerification:"Administrator verification",cinRequired:"Enter your CIN to verify your identity.",verify:"Verify",loginText:"Sign in to your account",login:"Login",register:"Register",forgot:"Forgot password",noEvents:"No real events are available right now.",oddsUnavailable:"Odds are unavailable on your Sportmonks plan.",playerAccount:"Player Account",agentAccount:"Agent Account",adminAccount:"Administrator",pending:"Pending",approved:"Approved",rejected:"Rejected",none:"Not agent"},
es:{home:"Inicio",sports:"Deportes",tickets:"Boletos",wallet:"Billetera",exchange:"Cambio",history:"Historial",profile:"Mi perfil",agentSpace:"Espacio Agente",admin:"Administración",logout:"Cerrar sesión",realEvents:"Eventos reales",heroTitle:"Apuesta en partidos reales.",heroText:"Los eventos de fútbol vienen directamente de Sportmonks.",seeBets:"Ver apuestas",manageWallet:"Gestionar billetera",balance:"Saldo",openEvents:"Eventos abiertos",account:"Cuenta",realMatches:"Partidos reales",liveSource:"Sportmonks • sin partidos demo",footballFirst:"El fútbol real está conectado; otros deportes necesitan sus propias fuentes de datos.",poolRule:"Los pagos de ganadores salen del fondo del 60% del evento.",event:"Evento",selection:"Selección",stake:"Apuesta",currency:"Moneda",placeBet:"Apostar",walletText:"Depósitos, retiros y saldos.",mainBalance:"Saldo principal",deposit:"Depositar",withdraw:"Retirar",amount:"Monto",phone:"Teléfono",continue:"Continuar",exchangeText:"Convierte tu saldo con tasas actuales.",from:"De",to:"A",accountType:"Tipo de cuenta",agentStatus:"Estado del agente",agentCode:"Código de agente",linkedAgent:"Agente vinculado",becomeAgent:"Convertirse en Agente",agentApproval:"El admin debe aprobar la solicitud.",fullName:"Nombre completo",city:"Ciudad",address:"Dirección",sendRequest:"Enviar solicitud",agentOnly:"Solo agentes aprobados.",players:"Jugadores",commission:"Comisión",linkedPlayers:"Jugadores vinculados",createPlayerTicket:"Crear ticket para un jugador",createTicket:"Crear ticket",cinProtected:"Esta zona está protegida por CIN.",users:"Usuarios",openBets:"Apuestas abiertas",platformBalance:"Saldo de plataforma",agentRequests:"Solicitudes de agentes",settleEvent:"Liquidar evento",result:"Resultado",settle:"Liquidar",adminVerification:"Verificación de Administrador",cinRequired:"Ingrese su CIN para verificar su identidad.",verify:"Verificar",loginText:"Inicia sesión en tu cuenta",login:"Ingresar",register:"Registrarse",forgot:"Olvidé mi contraseña",noEvents:"No hay eventos reales disponibles ahora.",oddsUnavailable:"Las cuotas no están disponibles en su plan Sportmonks.",playerAccount:"Cuenta Jugador",agentAccount:"Cuenta Agente",adminAccount:"Administrador",pending:"Pendiente",approved:"Aprobado",rejected:"Rechazado",none:"No agente"}
};
const tr=k=>T[state.language]?.[k]||T.ht[k]||k;
function applyLanguage(){document.documentElement.lang=state.language;document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=tr(el.dataset.i18n));$("language").value=state.language;renderProfile();renderEvents();}
function toast(msg){const el=$("toast");if(!el)return;el.textContent=msg;el.classList.add("show");clearTimeout(window.__t);window.__t=setTimeout(()=>el.classList.remove("show"),2600);}
function money(n,c="HTG"){return `${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})} ${c}`;}
async function api(path,opt={}){const headers={"Content-Type":"application/json",...(opt.headers||{})};if(state.user)headers.Authorization=`Bearer ${await state.user.getIdToken()}`;if(state.adminSession&&path.startsWith("/api/admin/"))headers["X-Admin-Session"]=state.adminSession;const r=await fetch(API+path,{...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||"Server error");e.status=r.status;e.data=d;throw e;}return d;}
const isAdmin=()=>state.me?.isAdmin===true||state.me?.canAccessAdmin===true||state.me?.role==="admin";
const isAgent=()=>state.me?.isApprovedAgent===true||state.me?.canAccessAgent===true||(state.me?.role==="agent"&&state.me?.agentStatus==="approved");
function roleText(){return isAdmin()?tr("adminAccount"):isAgent()?tr("agentAccount"):tr("playerAccount");}
function openSide(){$("side").classList.remove("hidden");$("sideBackdrop").classList.remove("hidden");}
function closeSide(){$("side").classList.add("hidden");$("sideBackdrop").classList.add("hidden");}
function openPage(page){if(page==="agent"&&!isAgent())page="profile";if(page==="admin"&&!isAdmin())page="profile";document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$("page-"+page)?.classList.remove("hidden");closeSide();if(page==="wallet")loadWallet();if(page==="history")loadHistory();if(page==="agent")loadAgent();if(page==="admin")loadAdmin();}
function applyRoleUI(){const a=isAdmin(),g=isAgent();$("adminNav")?.classList.toggle("hidden",!a);$("agentNav")?.classList.toggle("hidden",!g);const p=$("agentApplication");if(p)p.classList.toggle("hidden",a||g||state.me?.agentStatus==="pending");}
function renderProfile(){if(!state.me)return;const role=roleText();$("profileName").textContent=state.me.fullName||state.me.email?.split("@")[0]||"User";$("profileRole").textContent=role;$("profileEmail").textContent=state.me.email||"-";$("profileType").textContent=role;$("profileAgentStatus").textContent=tr(state.me.agentStatus||"none");$("profileAgentCode").textContent=state.me.agentCode||"-";$("profileLinkedAgent").textContent=state.me.linkedAgent||"-";$("sideRole").textContent=role;$("homeRole").textContent=role;applyRoleUI();}
function oddsVal(e,k){return e.markets?.[k]??e.odds?.[k]??null;}
function eventCard(e){const h=oddsVal(e,"home"),d=oddsVal(e,"draw"),a=oddsVal(e,"away"),has=[h,d,a].some(v=>Number(v)>0);return `<article class="event-card"><div class="event-header"><div><div class="event-league">${e.league||"Football"}</div><div class="event-time">${e.start||e.startingAt||""}</div></div><strong>#${e.id}</strong></div><div class="event-teams"><strong>${e.home||"Home"}</strong><span>vs</span><strong>${e.away||"Away"}</strong></div>${has?`<div class="odds-buttons"><button class="odd-btn" data-event="${e.id}" data-market="home"><span>1</span>${h??"-"}</button><button class="odd-btn" data-event="${e.id}" data-market="draw"><span>X</span>${d??"-"}</button><button class="odd-btn" data-event="${e.id}" data-market="away"><span>2</span>${a??"-"}</button></div>`:`<div class="info-box">${tr("oddsUnavailable")}</div>`}</article>`;}
function renderEvents(){const list=state.events.filter(e=>(e.sport||"Football").toLowerCase()==="football");$("homeOpenEvents").textContent=list.length;$("homeEvents").innerHTML=list.length?list.slice(0,8).map(eventCard).join(""):`<div class="empty">${tr("noEvents")}</div>`;$("eventsList").innerHTML=list.length?list.map(eventCard).join(""):`<div class="empty">${tr("noEvents")}</div>`;const opts=list.map(e=>`<option value="${e.id}">${e.home} - ${e.away}</option>`).join("");$("betEventId").innerHTML=opts;$("agentEventId").innerHTML=opts;$("adminEventSelect").innerHTML=opts;document.querySelectorAll(".odd-btn").forEach(b=>b.onclick=()=>{openPage("bet");$("betEventId").value=b.dataset.event;$("betMarket").value=b.dataset.market;updateSelectedOdds();});}
async function loadEvents(){try{const d=await api("/api/events");state.events=Array.isArray(d.items)?d.items:[];renderEvents();}catch(e){toast(e.message);state.events=[];renderEvents();}}
function renderSports(){const sports=[["Football","⚽"],["Basketball","🏀"],["Baseball","⚾"],["Tennis","🎾"],["Volleyball","🏐"],["Hockey","🏒"],["Boxing/MMA","🥊"],["Horse racing","🏇"],["Esports","🎮"],["Lottery","🎱"],["Borlette","🔢"],["Virtual football","🖥️"],["Virtual basketball","🏀"],["Jackpot","💎"],["Live betting","🔴"]];$("sportCategories").innerHTML=sports.map(([n,i])=>`<button class="sport-card ${n==="Football"?"active":""}" data-sport="${n}"><span class="sport-icon">${i}</span><strong>${n}</strong></button>`).join("");document.querySelectorAll("[data-sport]").forEach(b=>b.onclick=()=>{if(b.dataset.sport!=="Football")toast(tr("footballFirst"));});}
function updateSelectedOdds(){const e=state.events.find(x=>String(x.id)===String($("betEventId").value)),m=$("betMarket").value;$("selectedOdds").textContent=e&&Number(oddsVal(e,m))>0?`Odds: ${oddsVal(e,m)}`:tr("oddsUnavailable");}
async function placeBet(){try{const e=state.events.find(x=>String(x.id)===String($("betEventId").value));if(!e)throw new Error(tr("noEvents"));const m=$("betMarket").value;if(!(Number(oddsVal(e,m))>0))throw new Error(tr("oddsUnavailable"));const d=await api("/api/bet",{method:"POST",body:JSON.stringify({eventId:String(e.id),market:m,stake:Number($("betStake").value),currency:state.currency})});$("betMsg").textContent=d.message||"OK";await loadWallet();}catch(e){$("betMsg").textContent=e.message;}}
function renderWallet(){$("currencyBalances").innerHTML=Object.entries(state.wallet).map(([c,v])=>`<div class="currency-card"><span>${c}</span><strong>${money(v,c)}</strong></div>`).join("");$("walletMainBalance").textContent=money(state.wallet[state.currency]||0,state.currency);$("homeBalance").textContent=money(state.wallet[state.currency]||0,state.currency);$("ticketCurrency").textContent=state.currency;}
async function loadWallet(){try{const d=await api("/api/wallet");state.wallet={...state.wallet,...(d.balances||{})};renderWallet();}catch(e){$("walletMsg").textContent=e.message;}}
async function loadHistory(){try{const d=await api("/api/history");const items=d.items||d.transactions||[];$("historyList").innerHTML=items.length?items.map(x=>`<div class="history-item"><div><strong>${x.type}</strong><small>${x.created_at||""}</small></div><strong>${money(x.amount,x.currency)}</strong></div>`).join(""):`<div class="empty">-</div>`;}catch(e){toast(e.message);}}
async function exchange(){try{const d=await api("/api/exchange",{method:"POST",body:JSON.stringify({from:$("exchangeFrom").value,to:$("exchangeTo").value,amount:Number($("exchangeAmount").value)})});$("exchangeMsg").textContent=`${money(d.received,d.to||$("exchangeTo").value)}`;await loadWallet();}catch(e){$("exchangeMsg").textContent=e.message;}}
async function payment(){try{const amount=Number($("paymentAmount").value),phone=$("paymentPhone").value.trim();if(state.paymentMethod==="natcash")throw new Error("NatCash merchant API poko konfigire.");const path=state.paymentMode==="deposit"?"/api/payment/moncash/deposit":"/api/payment/moncash/withdraw";const d=await api(path,{method:"POST",body:JSON.stringify({amount,phone})});if(d.redirectUrl){location.href=d.redirectUrl;return;}$("walletMsg").textContent=d.message||"OK";await loadWallet();}catch(e){$("walletMsg").textContent=e.message;}}
async function applyAgent(){try{await api("/api/agent/apply",{method:"POST",body:JSON.stringify({name:$("agentName").value.trim(),phone:$("agentPhone").value.trim(),city:$("agentCity").value.trim(),address:$("agentAddress").value.trim(),cin:$("agentCin").value.trim()})});$("agentApplyMsg").textContent="OK";await loadMe();}catch(e){$("agentApplyMsg").textContent=e.message;}}
async function loadAgent(){if(!isAgent())return;try{const d=await api("/api/agent/dashboard");$("agentCodeDisplay").textContent=d.agentCode||state.me.agentCode||"-";$("agentPlayerCount").textContent=d.players?.length||0;$("agentCommission").textContent=money(d.commission||0,"HTG");$("agentPlayers").innerHTML=(d.players||[]).map(p=>`<div class="profile-line"><span>${p.email||p.uid}</span><strong>${p.uid.slice(0,8)}...</strong></div>`).join("")||"-";$("agentPlayerSelect").innerHTML=(d.players||[]).map(p=>`<option value="${p.uid}">${p.email||p.uid}</option>`).join("");}catch(e){$("agentMsg").textContent=e.message;}}
async function agentBet(){try{await api("/api/agent/bet",{method:"POST",body:JSON.stringify({playerUid:$("agentPlayerSelect").value,eventId:$("agentEventId").value,market:$("agentMarket").value,stake:Number($("agentStake").value),currency:"HTG"})});$("agentMsg").textContent="OK";}catch(e){$("agentMsg").textContent=e.message;}}
function showCin(){if(!isAdmin())return;$("adminNameBox").classList.toggle("hidden",state.me?.cinConfigured===true);$("cinModal").classList.remove("hidden");}
async function verifyCin(){try{const setup=state.me?.cinConfigured!==true;const d=await api(setup?"/api/admin/cin/setup":"/api/admin/cin/verify",{method:"POST",body:JSON.stringify({cin:$("adminCin").value.trim(),fullName:$("adminFullName").value.trim()})});state.adminSession=d.session;sessionStorage.setItem("mp_admin_session",d.session);state.me.cinConfigured=true;$("cinModal").classList.add("hidden");openPage("admin");}catch(e){$("adminCinMsg").textContent=e.message;}}
async function loadAdmin(){if(!isAdmin())return;if(!state.adminSession){showCin();return;}try{const [s,a]=await Promise.all([api("/api/admin/stats"),api("/api/admin/agents")]);$("adminUsers").textContent=s.users||0;$("adminOpenBets").textContent=s.openBets||0;$("adminPlatform").textContent=money(s.platformBalance||0,"HTG");$("adminAgents").innerHTML=(a.agents||[]).map(x=>`<div class="profile-line"><span>${x.name||x.uid}<small>${x.status}</small></span>${x.status==="pending"?`<span><button onclick="reviewAgent('${x.uid}','approved')">✓</button><button onclick="reviewAgent('${x.uid}','rejected')">✕</button></span>`:`<strong>${x.status}</strong>`}</div>`).join("")||"-";}catch(e){if(e.status===401){state.adminSession="";sessionStorage.removeItem("mp_admin_session");showCin();}$("adminMsg").textContent=e.message;}}
window.reviewAgent=async(uid,status)=>{try{await api("/api/admin/agent-review",{method:"POST",body:JSON.stringify({uid,status})});loadAdmin();}catch(e){$("adminMsg").textContent=e.message;}};
async function settle(){try{await api("/api/admin/settle",{method:"POST",body:JSON.stringify({eventId:$("adminEventSelect").value,winner:$("adminWinner").value})});$("adminMsg").textContent="OK";}catch(e){$("adminMsg").textContent=e.message;}}
async function loadMe(){state.me=await api("/api/me");renderProfile();if(isAdmin()&&!state.adminSession)showCin();}
async function clearLegacyCache(){const v="mp42";if(localStorage.getItem("mp_cache_version")===v)return;try{for(const r of await navigator.serviceWorker?.getRegistrations?.()||[])await r.unregister();for(const k of await caches?.keys?.()||[])await caches.delete(k);}catch{}localStorage.setItem("mp_cache_version",v);}
function bind(){$("menuBtn").onclick=openSide;$("closeSide").onclick=closeSide;$("sideBackdrop").onclick=closeSide;$("profileBtn").onclick=()=>openPage("profile");document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>openPage(b.dataset.page));document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openPage(b.dataset.open));$("language").onchange=e=>{state.language=e.target.value;localStorage.setItem("mp_language",state.language);applyLanguage();};$("currency").value=state.currency;$("currency").onchange=e=>{state.currency=e.target.value;localStorage.setItem("mp_currency",state.currency);renderWallet();};$("refreshEvents").onclick=loadEvents;$("betEventId").onchange=updateSelectedOdds;$("betMarket").onchange=updateSelectedOdds;$("placeBetBtn").onclick=placeBet;document.querySelectorAll("[data-wallet-action]").forEach(b=>b.onclick=()=>{state.paymentMode=b.dataset.walletAction;$("paymentPanel").classList.remove("hidden");$("paymentPhoneBox").classList.toggle("hidden",state.paymentMode!=="withdraw");$("paymentTitle").textContent=state.paymentMode==="deposit"?tr("deposit"):tr("withdraw");});document.querySelectorAll("[data-payment-method]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-payment-method]").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.paymentMethod=b.dataset.paymentMethod;});$("paymentBtn").onclick=payment;$("exchangeBtn").onclick=exchange;$("agentApplyBtn").onclick=applyAgent;$("agentBetBtn").onclick=agentBet;$("adminCinBtn").onclick=verifyCin;$("adminSettleBtn").onclick=settle;$("logoutBtn").onclick=()=>window.MPAuth.logout();$("profileLogoutBtn").onclick=()=>window.MPAuth.logout();$("loginBtn").onclick=async()=>{try{await window.MPAuth.login($("authEmail").value.trim(),$("authPassword").value);}catch(e){$("authMsg").textContent=e.message;}};$("registerBtn").onclick=async()=>{try{await window.MPAuth.register($("authEmail").value.trim(),$("authPassword").value);}catch(e){$("authMsg").textContent=e.message;}};$("resetBtn").onclick=async()=>{try{await window.MPAuth.resetPassword($("authEmail").value.trim());$("authMsg").textContent="OK";}catch(e){$("authMsg").textContent=e.message;}};}
function waitAuth(){if(!window.MPAuth?.onAuthStateChanged)return setTimeout(waitAuth,100);window.MPAuth.onAuthStateChanged(async user=>{state.user=user;if(!user){state.me=null;$("authOverlay").classList.remove("hidden");$("adminNav").classList.add("hidden");$("agentNav").classList.add("hidden");return;}$("authOverlay").classList.add("hidden");try{await Promise.all([loadMe(),loadWallet(),loadEvents()]);}catch(e){toast(e.message);}});}
(async()=>{await clearLegacyCache();bind();renderSports();applyLanguage();waitAuth();})();
